### ISSUE TITLE
Laravel 5.4 Segmentation Fault

### ISSUE THREAD

**Issue by jonathan-bird** [spatie/laravel-failed-job-monitor#31] opened 2017-03-12 09:59 UTC
On Laravel 5.4 when you install this library, you get a seg fault error when running any php artisan command.

```
php artisan view:clear
Compiled views cleared!
Segmentation fault (core dumped)
```

**Comment by jonathan-bird** [comment] 2017-03-12 10:00
Really useful library, would love it could get fixed so I can reinstall!

**Comment by jonathan-bird** [comment] 2017-03-14 00:02
Think it's to do with app->make not being supported. There's a new makeWith function.

**Comment by AlexVanderbist** [comment] 2017-03-14 09:10
Hi @jonathan-bird 

I couldn't seem to replicate the issue on a clean Laravel 5.4 project (PHP 7.1). Could provide some more information on the steps you took to get to the segmentation fault? I might be missing something.

Also what `makeWith` method do you mean? I've been looking through the Laravel docs/source but couldn't find anything on it.

Thanks

**Comment by jonathan-bird** [comment] 2017-04-09 23:26
Makewith since 5.4.16 - https://github.com/laravel/framework/blob/b2b1f990cff05b8e98dc28afac68ba4fe8da0cef/CHANGELOG-5.4.md#added-1

I dug deeper and although I think this package was showing the seg fault, it was a more deep rooted issue. It was a while ago now so can't remember, but safe to say it wasn't this.

**Comment by freekmurze** [comment] 2017-04-10 08:36
Closing this for now because we can't reproduce this problem.

**Closed by freekmurze** 2017-04-10 08:36 UTC
